version: "2"
services:

  go-httpguard:
    image: ppcelery/go-httpguard:0.1
    restart: "on-failure"
    networks:
      - go-httpguard
    logging:
      # driver: "json-file"
      # options:
      #   max-size: 10m
      driver: "fluentd"
      options:
        tag: httpguard.sit
        fluentd-address: hbase1.sit.ptcloud.t.home:24225
    environment:
      - TASKS=heartbeat,es-monitor,fl-monitor,es-rollover
    volumes:
      - /opt/configs/go-httpguard:/etc/go-httpguard
    ports:
      - 24215:24215

networks:
  go-httpguard:
    driver: bridge
