listen: "0.0.0.0:24215"
backend: "http://100.97.108.34:8333"
bypass:
  read:
    - "/"
users:
  - username: "laisky"
    basic_auth:
      enable: true
      password: "laisky"
    s3:
      enable: true
      app_secret: "laisky"
    jwt:
      enable: true
    permission:
      read:
        - "/"
      write:
        - "/test"
